export const teamdataset = [
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    ['jays alimi', 'jaysalimi.msme@gmail.com', 'designer', '2 minute ago',],
    
   
];